"""Official Thesis Research Model Evaluation Metrics"""
OFFICIAL_RESEARCH_METRICS = {   'accuracy': 0.8373,
    'adjustment_enabled': True,
    'base_scale_pos_weight': 0.9113,
    'baseline': {   'accuracy': 0.8373,
                    'base_scale_pos_weight': 0.9113,
                    'classification_threshold': 0.39,
                    'f1': 0.8928,
                    'feature_count': 18,
                    'feature_names': [   'recency_ratio',
                                         'frequency_trend_smoothed',
                                         'spend_trend_smoothed',
                                         'recency_days',
                                         'tx_count_90d',
                                         'spend_90d',
                                         'avg_tx_value',
                                         'tenure_days',
                                         'activity_mean',
                                         'recent_activity_avg',
                                         'activity_std',
                                         'activity_cv',
                                         'spend_volatility_cv',
                                         'trend_magnitude_interaction',
                                         'homecare_tx_ratio_90d',
                                         'last_tx_is_homecare',
                                         'zero_amount_tx_count_90d',
                                         'lifetime_tx_count'],
                    'model_type': 'baseline',
                    'neutralized_model_features': [   'tenure_days',
                                                      'avg_sentiment_score',
                                                      'sentiment_trend'],
                    'observation_dates': [   '2023-06-01',
                                             '2023-07-01',
                                             '2023-08-01',
                                             '2023-09-01',
                                             '2023-10-01',
                                             '2023-11-01',
                                             '2023-12-01',
                                             '2024-01-01',
                                             '2024-02-01',
                                             '2024-03-01',
                                             '2024-04-01',
                                             '2024-05-01',
                                             '2024-06-01',
                                             '2024-07-01',
                                             '2024-08-01',
                                             '2024-09-01',
                                             '2024-10-01',
                                             '2024-11-01',
                                             '2024-12-01',
                                             '2025-01-01',
                                             '2025-02-01',
                                             '2025-03-01',
                                             '2025-04-01',
                                             '2025-05-01',
                                             '2025-06-01',
                                             '2025-07-01',
                                             '2025-08-01',
                                             '2025-09-01',
                                             '2025-10-01',
                                             '2025-11-01',
                                             '2025-12-01',
                                             '2026-01-01',
                                             '2026-02-01',
                                             '2026-03-01',
                                             '2026-04-01',
                                             '2026-05-01',
                                             '2026-06-01',
                                             '2026-06-04'],
                    'original_negative_labels': 7648,
                    'original_positive_labels': 8392,
                    'original_train_size': 16040,
                    'pr_auc': 0.9469,
                    'precision': 0.8789,
                    'prediction_horizon_days': 90,
                    'purged_observation_dates': ['2025-10-01', '2025-11-01'],
                    'purged_size': 3822,
                    'recall': 0.9071,
                    'roc_auc': 0.8712,
                    'scale_pos_weight': 1.1392,
                    'scale_pos_weight_multiplier': 1.25,
                    'smote_applied': False,
                    'split_observation_date': '2025-12-01',
                    'split_strategy': 'purged_time_based',
                    'test_negative_labels': 4853,
                    'test_observation_dates': [   '2025-12-01',
                                                  '2026-01-01',
                                                  '2026-02-01',
                                                  '2026-03-01',
                                                  '2026-04-01',
                                                  '2026-05-01',
                                                  '2026-06-01',
                                                  '2026-06-04'],
                    'test_positive_labels': 14318,
                    'test_size': 19171,
                    'text_coverage_test': 0.1263,
                    'text_coverage_train': 0.1763,
                    'threshold_sensitivity': [   {   'f1_score': 0.8954,
                                                     'high_risk_customers': 15616,
                                                     'precision': 0.8582,
                                                     'recall': 0.936,
                                                     'threshold': 0.3},
                                                 {   'f1_score': 0.8928,
                                                     'high_risk_customers': 14777,
                                                     'precision': 0.8789,
                                                     'recall': 0.9071,
                                                     'threshold': 0.39},
                                                 {   'f1_score': 0.8921,
                                                     'high_risk_customers': 14695,
                                                     'precision': 0.8806,
                                                     'recall': 0.9038,
                                                     'threshold': 0.4},
                                                 {   'f1_score': 0.8823,
                                                     'high_risk_customers': 13897,
                                                     'precision': 0.8957,
                                                     'recall': 0.8693,
                                                     'threshold': 0.5},
                                                 {   'f1_score': 0.8545,
                                                     'high_risk_customers': 12471,
                                                     'precision': 0.9177,
                                                     'recall': 0.7993,
                                                     'threshold': 0.6},
                                                 {   'f1_score': 0.8245,
                                                     'high_risk_customers': 11323,
                                                     'precision': 0.9336,
                                                     'recall': 0.7383,
                                                     'threshold': 0.7}],
                    'train_observation_dates': [   '2023-06-01',
                                                   '2023-07-01',
                                                   '2023-08-01',
                                                   '2023-09-01',
                                                   '2023-10-01',
                                                   '2023-11-01',
                                                   '2023-12-01',
                                                   '2024-01-01',
                                                   '2024-02-01',
                                                   '2024-03-01',
                                                   '2024-04-01',
                                                   '2024-05-01',
                                                   '2024-06-01',
                                                   '2024-07-01',
                                                   '2024-08-01',
                                                   '2024-09-01',
                                                   '2024-10-01',
                                                   '2024-11-01',
                                                   '2024-12-01',
                                                   '2025-01-01',
                                                   '2025-02-01',
                                                   '2025-03-01',
                                                   '2025-04-01',
                                                   '2025-05-01',
                                                   '2025-06-01',
                                                   '2025-07-01',
                                                   '2025-08-01',
                                                   '2025-09-01'],
                    'train_size': 16040,
                    'xgb_params': {   'colsample_bytree': 1.0,
                                      'gamma': 0.1,
                                      'learning_rate': 0.03,
                                      'max_depth': 3,
                                      'min_child_weight': 5,
                                      'n_estimators': 200,
                                      'reg_alpha': 0.1,
                                      'reg_lambda': 2.0,
                                      'subsample': 1.0}},
    'classification_threshold': 0.39,
    'comparison_interpretation': 'Multimodal model improves ROC-AUC by 0.006 '
                                 'and Recall by 0.418 on communication cohort '
                                 'compared to the transaction-only baseline. '
                                 'This indicates that customer interaction '
                                 'signals contribute additional predictive '
                                 'value beyond transactional behavior.',
    'f1': 0.8928,
    'feature_count': 25,
    'feature_names': [   'recency_ratio',
                         'frequency_trend_smoothed',
                         'spend_trend_smoothed',
                         'msg_trend_smoothed',
                         'sentiment_trend',
                         'recency_days',
                         'tx_count_90d',
                         'spend_90d',
                         'avg_tx_value',
                         'tenure_days',
                         'activity_mean',
                         'recent_activity_avg',
                         'activity_std',
                         'activity_cv',
                         'spend_volatility_cv',
                         'trend_magnitude_interaction',
                         'avg_sentiment_score',
                         'complaint_ratio',
                         'msg_volatility',
                         'response_delay_mean',
                         'has_communication_90d',
                         'homecare_tx_ratio_90d',
                         'last_tx_is_homecare',
                         'zero_amount_tx_count_90d',
                         'lifetime_tx_count'],
    'gated_adjuster': {   'adjustment_enabled': True,
                          'base_on_multimodal_cohort': {   'accuracy': 0.8202,
                                                           'classification_threshold': 0.39,
                                                           'f1': 0.3215,
                                                           'pr_auc': 0.2807,
                                                           'precision': 0.2969,
                                                           'recall': 0.3506,
                                                           'roc_auc': 0.7325},
                          'folds': 5,
                          'gated_logistic': {   'accuracy': 0.5645,
                                                'classification_threshold': 0.39,
                                                'f1': 0.3001,
                                                'pr_auc': 0.3204,
                                                'precision': 0.1865,
                                                'recall': 0.7686,
                                                'roc_auc': 0.7381},
                          'improvement': {   'f1': -0.0214,
                                             'pr_auc': 0.0397,
                                             'precision': -0.1104,
                                             'recall': 0.418,
                                             'roc_auc': 0.0056},
                          'meta_feature_names': [   'base_risk_score',
                                                    'complaint_ratio',
                                                    'msg_trend_smoothed',
                                                    'log_response_delay_mean'],
                          'negative_labels': 5156,
                          'positive_labels': 713,
                          'rows': 5869,
                          'unique_customers': 361,
                          'validation_strategy': 'stratified_group_kfold_by_customer'},
    'improvement': {   'f1': -0.0214,
                       'pr_auc': 0.0397,
                       'precision': -0.1104,
                       'recall': 0.418,
                       'roc_auc': 0.0056},
    'model_type': 'gated_transaction_xgb_logistic',
    'multimodal': {   'accuracy': 0.8373,
                      'adjustment_enabled': True,
                      'base_scale_pos_weight': 0.9113,
                      'classification_threshold': 0.39,
                      'f1': 0.8928,
                      'feature_count': 25,
                      'feature_names': [   'recency_ratio',
                                           'frequency_trend_smoothed',
                                           'spend_trend_smoothed',
                                           'msg_trend_smoothed',
                                           'sentiment_trend',
                                           'recency_days',
                                           'tx_count_90d',
                                           'spend_90d',
                                           'avg_tx_value',
                                           'tenure_days',
                                           'activity_mean',
                                           'recent_activity_avg',
                                           'activity_std',
                                           'activity_cv',
                                           'spend_volatility_cv',
                                           'trend_magnitude_interaction',
                                           'avg_sentiment_score',
                                           'complaint_ratio',
                                           'msg_volatility',
                                           'response_delay_mean',
                                           'has_communication_90d',
                                           'homecare_tx_ratio_90d',
                                           'last_tx_is_homecare',
                                           'zero_amount_tx_count_90d',
                                           'lifetime_tx_count'],
                      'gated_adjuster': {   'adjustment_enabled': True,
                                            'base_on_multimodal_cohort': {   'accuracy': 0.8202,
                                                                             'classification_threshold': 0.39,
                                                                             'f1': 0.3215,
                                                                             'pr_auc': 0.2807,
                                                                             'precision': 0.2969,
                                                                             'recall': 0.3506,
                                                                             'roc_auc': 0.7325},
                                            'folds': 5,
                                            'gated_logistic': {   'accuracy': 0.5645,
                                                                  'classification_threshold': 0.39,
                                                                  'f1': 0.3001,
                                                                  'pr_auc': 0.3204,
                                                                  'precision': 0.1865,
                                                                  'recall': 0.7686,
                                                                  'roc_auc': 0.7381},
                                            'improvement': {   'f1': -0.0214,
                                                               'pr_auc': 0.0397,
                                                               'precision': -0.1104,
                                                               'recall': 0.418,
                                                               'roc_auc': 0.0056},
                                            'meta_feature_names': [   'base_risk_score',
                                                                      'complaint_ratio',
                                                                      'msg_trend_smoothed',
                                                                      'log_response_delay_mean'],
                                            'negative_labels': 5156,
                                            'positive_labels': 713,
                                            'rows': 5869,
                                            'unique_customers': 361,
                                            'validation_strategy': 'stratified_group_kfold_by_customer'},
                      'model_type': 'gated_transaction_xgb_logistic',
                      'neutralized_model_features': [   'tenure_days',
                                                        'avg_sentiment_score',
                                                        'sentiment_trend',
                                                        'msg_trend_smoothed',
                                                        'complaint_ratio',
                                                        'msg_volatility',
                                                        'response_delay_mean',
                                                        'has_communication_90d'],
                      'observation_dates': [   '2023-06-01',
                                               '2023-07-01',
                                               '2023-08-01',
                                               '2023-09-01',
                                               '2023-10-01',
                                               '2023-11-01',
                                               '2023-12-01',
                                               '2024-01-01',
                                               '2024-02-01',
                                               '2024-03-01',
                                               '2024-04-01',
                                               '2024-05-01',
                                               '2024-06-01',
                                               '2024-07-01',
                                               '2024-08-01',
                                               '2024-09-01',
                                               '2024-10-01',
                                               '2024-11-01',
                                               '2024-12-01',
                                               '2025-01-01',
                                               '2025-02-01',
                                               '2025-03-01',
                                               '2025-04-01',
                                               '2025-05-01',
                                               '2025-06-01',
                                               '2025-07-01',
                                               '2025-08-01',
                                               '2025-09-01',
                                               '2025-10-01',
                                               '2025-11-01',
                                               '2025-12-01',
                                               '2026-01-01',
                                               '2026-02-01',
                                               '2026-03-01',
                                               '2026-04-01',
                                               '2026-05-01',
                                               '2026-06-01',
                                               '2026-06-04'],
                      'original_negative_labels': 7648,
                      'original_positive_labels': 8392,
                      'original_train_size': 16040,
                      'pr_auc': 0.9469,
                      'precision': 0.8789,
                      'prediction_horizon_days': 90,
                      'production_refit_size': 39033,
                      'purged_observation_dates': ['2025-10-01', '2025-11-01'],
                      'purged_size': 3822,
                      'recall': 0.9071,
                      'roc_auc': 0.8712,
                      'scale_pos_weight': 1.1392,
                      'scale_pos_weight_multiplier': 1.25,
                      'shap_available': True,
                      'smote_applied': False,
                      'split_observation_date': '2025-12-01',
                      'split_strategy': 'purged_time_based',
                      'test_negative_labels': 4853,
                      'test_observation_dates': [   '2025-12-01',
                                                    '2026-01-01',
                                                    '2026-02-01',
                                                    '2026-03-01',
                                                    '2026-04-01',
                                                    '2026-05-01',
                                                    '2026-06-01',
                                                    '2026-06-04'],
                      'test_positive_labels': 14318,
                      'test_size': 19171,
                      'text_coverage_test': 0.1263,
                      'text_coverage_train': 0.1763,
                      'threshold_sensitivity': [   {   'f1_score': 0.8954,
                                                       'high_risk_customers': 15616,
                                                       'precision': 0.8582,
                                                       'recall': 0.936,
                                                       'threshold': 0.3},
                                                   {   'f1_score': 0.8928,
                                                       'high_risk_customers': 14777,
                                                       'precision': 0.8789,
                                                       'recall': 0.9071,
                                                       'threshold': 0.39},
                                                   {   'f1_score': 0.8921,
                                                       'high_risk_customers': 14695,
                                                       'precision': 0.8806,
                                                       'recall': 0.9038,
                                                       'threshold': 0.4},
                                                   {   'f1_score': 0.8823,
                                                       'high_risk_customers': 13897,
                                                       'precision': 0.8957,
                                                       'recall': 0.8693,
                                                       'threshold': 0.5},
                                                   {   'f1_score': 0.8545,
                                                       'high_risk_customers': 12471,
                                                       'precision': 0.9177,
                                                       'recall': 0.7993,
                                                       'threshold': 0.6},
                                                   {   'f1_score': 0.8245,
                                                       'high_risk_customers': 11323,
                                                       'precision': 0.9336,
                                                       'recall': 0.7383,
                                                       'threshold': 0.7}],
                      'train_observation_dates': [   '2023-06-01',
                                                     '2023-07-01',
                                                     '2023-08-01',
                                                     '2023-09-01',
                                                     '2023-10-01',
                                                     '2023-11-01',
                                                     '2023-12-01',
                                                     '2024-01-01',
                                                     '2024-02-01',
                                                     '2024-03-01',
                                                     '2024-04-01',
                                                     '2024-05-01',
                                                     '2024-06-01',
                                                     '2024-07-01',
                                                     '2024-08-01',
                                                     '2024-09-01',
                                                     '2024-10-01',
                                                     '2024-11-01',
                                                     '2024-12-01',
                                                     '2025-01-01',
                                                     '2025-02-01',
                                                     '2025-03-01',
                                                     '2025-04-01',
                                                     '2025-05-01',
                                                     '2025-06-01',
                                                     '2025-07-01',
                                                     '2025-08-01',
                                                     '2025-09-01'],
                      'train_size': 16040,
                      'xgb_params': {   'colsample_bytree': 1.0,
                                        'gamma': 0.1,
                                        'learning_rate': 0.03,
                                        'max_depth': 3,
                                        'min_child_weight': 5,
                                        'n_estimators': 200,
                                        'reg_alpha': 0.1,
                                        'reg_lambda': 2.0,
                                        'subsample': 1.0}},
    'neutralized_model_features': [   'tenure_days',
                                      'avg_sentiment_score',
                                      'sentiment_trend',
                                      'msg_trend_smoothed',
                                      'complaint_ratio',
                                      'msg_volatility',
                                      'response_delay_mean',
                                      'has_communication_90d'],
    'observation_dates': [   '2023-06-01',
                             '2023-07-01',
                             '2023-08-01',
                             '2023-09-01',
                             '2023-10-01',
                             '2023-11-01',
                             '2023-12-01',
                             '2024-01-01',
                             '2024-02-01',
                             '2024-03-01',
                             '2024-04-01',
                             '2024-05-01',
                             '2024-06-01',
                             '2024-07-01',
                             '2024-08-01',
                             '2024-09-01',
                             '2024-10-01',
                             '2024-11-01',
                             '2024-12-01',
                             '2025-01-01',
                             '2025-02-01',
                             '2025-03-01',
                             '2025-04-01',
                             '2025-05-01',
                             '2025-06-01',
                             '2025-07-01',
                             '2025-08-01',
                             '2025-09-01',
                             '2025-10-01',
                             '2025-11-01',
                             '2025-12-01',
                             '2026-01-01',
                             '2026-02-01',
                             '2026-03-01',
                             '2026-04-01',
                             '2026-05-01',
                             '2026-06-01',
                             '2026-06-04'],
    'original_negative_labels': 7648,
    'original_positive_labels': 8392,
    'original_train_size': 16040,
    'pr_auc': 0.9469,
    'precision': 0.8789,
    'prediction_horizon_days': 90,
    'production_refit_size': 39033,
    'purged_observation_dates': ['2025-10-01', '2025-11-01'],
    'purged_size': 3822,
    'recall': 0.9071,
    'roc_auc': 0.8712,
    'scale_pos_weight': 1.1392,
    'scale_pos_weight_multiplier': 1.25,
    'shap_available': True,
    'smote_applied': False,
    'split_observation_date': '2025-12-01',
    'split_strategy': 'purged_time_based',
    'test_negative_labels': 4853,
    'test_observation_dates': [   '2025-12-01',
                                  '2026-01-01',
                                  '2026-02-01',
                                  '2026-03-01',
                                  '2026-04-01',
                                  '2026-05-01',
                                  '2026-06-01',
                                  '2026-06-04'],
    'test_positive_labels': 14318,
    'test_size': 19171,
    'text_coverage_test': 0.1263,
    'text_coverage_train': 0.1763,
    'threshold_sensitivity': [   {   'f1_score': 0.8954,
                                     'high_risk_customers': 15616,
                                     'precision': 0.8582,
                                     'recall': 0.936,
                                     'threshold': 0.3},
                                 {   'f1_score': 0.8928,
                                     'high_risk_customers': 14777,
                                     'precision': 0.8789,
                                     'recall': 0.9071,
                                     'threshold': 0.39},
                                 {   'f1_score': 0.8921,
                                     'high_risk_customers': 14695,
                                     'precision': 0.8806,
                                     'recall': 0.9038,
                                     'threshold': 0.4},
                                 {   'f1_score': 0.8823,
                                     'high_risk_customers': 13897,
                                     'precision': 0.8957,
                                     'recall': 0.8693,
                                     'threshold': 0.5},
                                 {   'f1_score': 0.8545,
                                     'high_risk_customers': 12471,
                                     'precision': 0.9177,
                                     'recall': 0.7993,
                                     'threshold': 0.6},
                                 {   'f1_score': 0.8245,
                                     'high_risk_customers': 11323,
                                     'precision': 0.9336,
                                     'recall': 0.7383,
                                     'threshold': 0.7}],
    'train_observation_dates': [   '2023-06-01',
                                   '2023-07-01',
                                   '2023-08-01',
                                   '2023-09-01',
                                   '2023-10-01',
                                   '2023-11-01',
                                   '2023-12-01',
                                   '2024-01-01',
                                   '2024-02-01',
                                   '2024-03-01',
                                   '2024-04-01',
                                   '2024-05-01',
                                   '2024-06-01',
                                   '2024-07-01',
                                   '2024-08-01',
                                   '2024-09-01',
                                   '2024-10-01',
                                   '2024-11-01',
                                   '2024-12-01',
                                   '2025-01-01',
                                   '2025-02-01',
                                   '2025-03-01',
                                   '2025-04-01',
                                   '2025-05-01',
                                   '2025-06-01',
                                   '2025-07-01',
                                   '2025-08-01',
                                   '2025-09-01'],
    'train_size': 16040,
    'xgb_params': {   'colsample_bytree': 1.0,
                      'gamma': 0.1,
                      'learning_rate': 0.03,
                      'max_depth': 3,
                      'min_child_weight': 5,
                      'n_estimators': 200,
                      'reg_alpha': 0.1,
                      'reg_lambda': 2.0,
                      'subsample': 1.0}}
