"""add msg_id to feedback_features

Revision ID: 28a4ab1f4514
Revises: 025_feedback_raw_nullable
Create Date: 2026-05-17 16:03:36.804736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28a4ab1f4514'
down_revision = '025_feedback_raw_nullable'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_churn_labels_customer_id'), 'churn_labels', ['customer_id'], unique=False)
    op.create_index(op.f('ix_churn_labels_observation_date'), 'churn_labels', ['observation_date'], unique=False)
    op.alter_column('churn_predictions', 'features_used',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='Immutable snapshot of features at prediction time',
               existing_nullable=True)
    op.alter_column('churn_predictions', 'feature_as_of',
               existing_type=postgresql.TIMESTAMP(),
               comment='Exact timestamp features were computed (for Explainer)',
               existing_comment='Exact timestamp features were computed',
               existing_nullable=True)
    op.create_index(op.f('ix_customer_numeric_features_as_of_date'), 'customer_numeric_features', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_customer_numeric_features_customer_id'), 'customer_numeric_features', ['customer_id'], unique=False)
    op.drop_index(op.f('idx_text_semantics_sentiment_version'), table_name='customer_text_semantics')
    op.drop_index(op.f('idx_text_semantics_topic_version'), table_name='customer_text_semantics')
    op.create_index(op.f('ix_customer_text_semantics_as_of_date'), 'customer_text_semantics', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_customer_text_semantics_customer_id'), 'customer_text_semantics', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_text_semantics_sentiment_model_version'), 'customer_text_semantics', ['sentiment_model_version'], unique=False)
    op.create_index(op.f('ix_customer_text_semantics_topic_model_version'), 'customer_text_semantics', ['topic_model_version'], unique=False)
    op.create_index(op.f('ix_customer_text_signals_as_of_date'), 'customer_text_signals', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_customer_text_signals_customer_id'), 'customer_text_signals', ['customer_id'], unique=False)
    op.drop_index(op.f('idx_customers_provisional'), table_name='customers')
    op.create_index(op.f('ix_customers_is_provisional'), 'customers', ['is_provisional'], unique=False)
    op.drop_constraint(op.f('embedding_model_registry_model_hash_key'), 'embedding_model_registry', type_='unique')
    op.drop_index(op.f('idx_embedding_registry_active'), table_name='embedding_model_registry', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_embedding_registry_hash'), table_name='embedding_model_registry')
    op.create_index('idx_active_model', 'embedding_model_registry', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_embedding_model_registry_is_active'), 'embedding_model_registry', ['is_active'], unique=False)
    op.create_index(op.f('ix_embedding_model_registry_model_hash'), 'embedding_model_registry', ['model_hash'], unique=True)
    op.alter_column('feedback_features', 'link_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_feedback_features_embedding_version'), table_name='feedback_features')
    op.create_index(op.f('ix_feedback_features_embedding_model_version'), 'feedback_features', ['embedding_model_version'], unique=False)
    op.create_index(op.f('ix_feedback_features_link_id'), 'feedback_features', ['link_id'], unique=True)
    op.create_foreign_key(None, 'feedback_features', 'feedback_linked', ['link_id'], ['link_id'], ondelete='CASCADE')
    op.alter_column('feedback_linked', 'link_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'provisional'::character varying"))
    op.drop_index(op.f('idx_feedback_linked_customer'), table_name='feedback_linked')
    op.drop_index(op.f('idx_feedback_linked_msg'), table_name='feedback_linked')
    op.drop_index(op.f('idx_feedback_linked_status'), table_name='feedback_linked')
    op.create_index(op.f('ix_feedback_linked_customer_id'), 'feedback_linked', ['customer_id'], unique=False)
    op.create_index(op.f('ix_feedback_linked_link_status'), 'feedback_linked', ['link_status'], unique=False)
    op.create_index(op.f('ix_feedback_linked_msg_id'), 'feedback_linked', ['msg_id'], unique=True)
    op.alter_column('feedback_raw', 'phone_number',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_index(op.f('ix_feedback_raw_customer_id'), table_name='feedback_raw')
    op.create_index(op.f('ix_feedback_raw_phone_number'), 'feedback_raw', ['phone_number'], unique=False)
    op.drop_constraint(op.f('feedback_raw_customer_id_fkey'), 'feedback_raw', type_='foreignkey')
    op.drop_column('feedback_raw', 'customer_id')
    op.drop_index(op.f('idx_ml_registry_active'), table_name='ml_model_registry', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_ml_registry_hash'), table_name='ml_model_registry')
    op.drop_constraint(op.f('ml_model_registry_model_hash_key'), 'ml_model_registry', type_='unique')
    op.create_index('idx_ml_active_model', 'ml_model_registry', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_ml_model_registry_is_active'), 'ml_model_registry', ['is_active'], unique=False)
    op.create_index(op.f('ix_ml_model_registry_model_hash'), 'ml_model_registry', ['model_hash'], unique=True)
    op.alter_column('model_versions', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('shap_cache', 'shap_values',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('shap_cache', 'shap_top',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('shap_cache', 'nearest_messages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('topics', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('idx_topics_topic_idx'), table_name='topics')
    op.create_index(op.f('ix_topics_model_version'), 'topics', ['model_version'], unique=False)
    op.create_index(op.f('ix_topics_topic_idx'), 'topics', ['topic_idx'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_topic_idx'), table_name='topics')
    op.drop_index(op.f('ix_topics_model_version'), table_name='topics')
    op.create_index(op.f('idx_topics_topic_idx'), 'topics', ['topic_idx'], unique=False)
    op.alter_column('topics', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('shap_cache', 'nearest_messages',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shap_cache', 'shap_top',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('shap_cache', 'shap_values',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('model_versions', 'metrics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_ml_model_registry_model_hash'), table_name='ml_model_registry')
    op.drop_index(op.f('ix_ml_model_registry_is_active'), table_name='ml_model_registry')
    op.drop_index('idx_ml_active_model', table_name='ml_model_registry', postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint(op.f('ml_model_registry_model_hash_key'), 'ml_model_registry', ['model_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_ml_registry_hash'), 'ml_model_registry', ['model_hash'], unique=False)
    op.create_index(op.f('idx_ml_registry_active'), 'ml_model_registry', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.add_column('feedback_raw', sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('feedback_raw_customer_id_fkey'), 'feedback_raw', 'customers', ['customer_id'], ['customer_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_feedback_raw_phone_number'), table_name='feedback_raw')
    op.create_index(op.f('ix_feedback_raw_customer_id'), 'feedback_raw', ['customer_id'], unique=False)
    op.alter_column('feedback_raw', 'phone_number',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_index(op.f('ix_feedback_linked_msg_id'), table_name='feedback_linked')
    op.drop_index(op.f('ix_feedback_linked_link_status'), table_name='feedback_linked')
    op.drop_index(op.f('ix_feedback_linked_customer_id'), table_name='feedback_linked')
    op.create_index(op.f('idx_feedback_linked_status'), 'feedback_linked', ['link_status'], unique=False)
    op.create_index(op.f('idx_feedback_linked_msg'), 'feedback_linked', ['msg_id'], unique=True)
    op.create_index(op.f('idx_feedback_linked_customer'), 'feedback_linked', ['customer_id'], unique=False)
    op.alter_column('feedback_linked', 'link_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'provisional'::character varying"))
    op.drop_constraint(None, 'feedback_features', type_='foreignkey')
    op.drop_index(op.f('ix_feedback_features_link_id'), table_name='feedback_features')
    op.drop_index(op.f('ix_feedback_features_embedding_model_version'), table_name='feedback_features')
    op.create_index(op.f('idx_feedback_features_embedding_version'), 'feedback_features', ['embedding_model_version'], unique=False)
    op.alter_column('feedback_features', 'link_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_embedding_model_registry_model_hash'), table_name='embedding_model_registry')
    op.drop_index(op.f('ix_embedding_model_registry_is_active'), table_name='embedding_model_registry')
    op.drop_index('idx_active_model', table_name='embedding_model_registry', postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('idx_embedding_registry_hash'), 'embedding_model_registry', ['model_hash'], unique=False)
    op.create_index(op.f('idx_embedding_registry_active'), 'embedding_model_registry', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_unique_constraint(op.f('embedding_model_registry_model_hash_key'), 'embedding_model_registry', ['model_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_customers_is_provisional'), table_name='customers')
    op.create_index(op.f('idx_customers_provisional'), 'customers', ['is_provisional'], unique=False)
    op.drop_index(op.f('ix_customer_text_signals_customer_id'), table_name='customer_text_signals')
    op.drop_index(op.f('ix_customer_text_signals_as_of_date'), table_name='customer_text_signals')
    op.drop_index(op.f('ix_customer_text_semantics_topic_model_version'), table_name='customer_text_semantics')
    op.drop_index(op.f('ix_customer_text_semantics_sentiment_model_version'), table_name='customer_text_semantics')
    op.drop_index(op.f('ix_customer_text_semantics_customer_id'), table_name='customer_text_semantics')
    op.drop_index(op.f('ix_customer_text_semantics_as_of_date'), table_name='customer_text_semantics')
    op.create_index(op.f('idx_text_semantics_topic_version'), 'customer_text_semantics', ['topic_model_version'], unique=False)
    op.create_index(op.f('idx_text_semantics_sentiment_version'), 'customer_text_semantics', ['sentiment_model_version'], unique=False)
    op.drop_index(op.f('ix_customer_numeric_features_customer_id'), table_name='customer_numeric_features')
    op.drop_index(op.f('ix_customer_numeric_features_as_of_date'), table_name='customer_numeric_features')
    op.alter_column('churn_predictions', 'feature_as_of',
               existing_type=postgresql.TIMESTAMP(),
               comment='Exact timestamp features were computed',
               existing_comment='Exact timestamp features were computed (for Explainer)',
               existing_nullable=True)
    op.alter_column('churn_predictions', 'features_used',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='Immutable snapshot of features at prediction time',
               existing_nullable=True)
    op.drop_index(op.f('ix_churn_labels_observation_date'), table_name='churn_labels')
    op.drop_index(op.f('ix_churn_labels_customer_id'), table_name='churn_labels')
    # ### end Alembic commands ###
